--
-- file: migrations/0002.create-person.sql
--
CREATE TABLE PERSON
(
    PERSON_ID INT NOT NULL PRIMARY KEY,
    _ID VARCHAR(50) NOT NULL,
    GUID CHAR(36),
    HAS_DIED SMALLINT,
    BALANCE DECIMAL(12, 2),
    PICTURE VARCHAR(255),
    AGE INT,
    EYE_COLOR VARCHAR(100),
    NAME VARCHAR (255),
    GENDER VARCHAR(20),
    COMPANY_ID INT,
    EMAIL VARCHAR (255),
    PHONE VARCHAR (20),
    ADDRESS VARCHAR(255),
    ABOUT VARCHAR(2000),
    REGISTERED VARCHAR(255),
    TAGS VARCHAR(255),
    GREETING VARCHAR(255),
    FAVOURITE_FOOD VARCHAR(255)
);